# Generated by Django 5.2.4 on 2025-08-03 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('model_tech', 'Модель техники'), ('model_engine', 'Модель двигателя'), ('model_transmission', 'Модель трансмиссии'), ('model_drive_bridge', 'Модель ведущего моста'), ('model_control_bridge', 'Модель управляемого моста'), ('type_maintenance', 'Вид ТО'), ('node_fail', 'Узел отказа'), ('method_recovery', 'Способ восстановления')], max_length=32, verbose_name='Тип справочника')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CL', 'Клиент'), ('SO', 'Сервисная организация'), ('MR', 'Менеджер')], default='CL', max_length=2, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(error_messages={'unique': 'Номер используется'}, max_length=128, unique=True, verbose_name='Зав. № машины')),
                ('engine_number', models.CharField(error_messages={'unique': 'Номер используется'}, max_length=128, unique=True, verbose_name='Зав. № двигателя')),
                ('transmission_number', models.CharField(error_messages={'unique': 'Номер используется'}, max_length=128, unique=True, verbose_name='Зав. № трансмиссии')),
                ('drive_bridge_number', models.CharField(error_messages={'unique': 'Номер используется'}, max_length=128, unique=True, verbose_name='Зав. № ведущего моста')),
                ('control_bridge_number', models.CharField(error_messages={'unique': 'Номер используется'}, max_length=128, unique=True, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=128, verbose_name='Договор поставки №, дата')),
                ('shipping_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('recipient', models.CharField(max_length=128, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=128, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(limit_choices_to={'type': 'CL'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('control_bridge_model', models.ForeignKey(limit_choices_to={'ref_type': 'model_control_bridge'}, on_delete=django.db.models.deletion.CASCADE, related_name='model_control_bridge', to='app.referencedirectory', verbose_name='Модель управляемого моста')),
                ('drive_bridge_model', models.ForeignKey(limit_choices_to={'ref_type': 'model_drive_bridge'}, on_delete=django.db.models.deletion.CASCADE, related_name='model_drive_bridge', to='app.referencedirectory', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(limit_choices_to={'ref_type': 'model_engine'}, on_delete=django.db.models.deletion.CASCADE, related_name='engine_models', to='app.referencedirectory', verbose_name='Модель двигателя')),
                ('service', models.ForeignKey(limit_choices_to={'type': 'SO'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'ref_type': 'model_transmission'}, on_delete=django.db.models.deletion.CASCADE, related_name='model_transmission', to='app.referencedirectory', verbose_name='Модель трансмиссии')),
                ('vehicle_model', models.ForeignKey(limit_choices_to={'ref_type': 'model_tech'}, on_delete=django.db.models.deletion.CASCADE, related_name='model_tech', to='app.referencedirectory', verbose_name='Модель техники')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(error_messages={'unique': 'Номер используется'}, max_length=128, unique=True, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('service', models.ForeignKey(blank=True, limit_choices_to={'type': 'SO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО')),
                ('maintenance_type', models.ForeignKey(limit_choices_to={'ref_type': 'type_maintenance'}, on_delete=django.db.models.deletion.CASCADE, related_name='type_maintenance', to='app.referencedirectory', verbose_name='Вид ТО')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_maintenance', to='app.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'TO',
                'verbose_name_plural': 'TO',
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('fail_description', models.CharField(max_length=128, verbose_name='Описание отказа')),
                ('spare_parts', models.CharField(blank=True, max_length=128, null=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(editable=False, verbose_name='Время простоя техники')),
                ('method_recovery', models.ForeignKey(limit_choices_to={'ref_type': 'method_recovery'}, on_delete=django.db.models.deletion.CASCADE, related_name='method_recovery', to='app.referencedirectory', verbose_name='Способ восстановления')),
                ('node_fail', models.ForeignKey(limit_choices_to={'re_type': 'node_fail'}, on_delete=django.db.models.deletion.CASCADE, related_name='node_fail', to='app.referencedirectory', verbose_name='Узел отказа')),
                ('service', models.ForeignKey(limit_choices_to={'type': 'SO'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_warranty_claim', to=settings.AUTH_USER_MODEL, verbose_name='Cервисная компания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_warranty_claim', to='app.vehicle', verbose_name='Mашина')),
            ],
        ),
    ]
